language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "lts/*"

install:
  - npm install
  - npm run build
  - cp install/iis/web.config dist/
  - cd dist
  - touch version.txt
  - echo $TRAVIS_TAG > version.txt
  - echo $TRAVIS_BUILD_NUMBER >> version.txt
  - zip -r ../release_$TRAVIS_TAG.zip .
  - cd ..


script: npm test

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release.zip
  skip_cleanup: true
  on:
    tags: true
